// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwKQ460poruMSbQFZ9OP8SAf_2y2Uxw0A',
    appId: '1:173813791952:web:f0dc6190c555572242b2d5',
    messagingSenderId: '173813791952',
    projectId: 'church-e2f46',
    authDomain: 'church-e2f46.firebaseapp.com',
    storageBucket: 'church-e2f46.firebasestorage.app',
    measurementId: 'G-9GNBHY38M9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzy4T1vCGhdIgnTuhFctX7_L54bnXBXIQ',
    appId: '1:173813791952:android:d29dc7ea0908623e42b2d5',
    messagingSenderId: '173813791952',
    projectId: 'church-e2f46',
    storageBucket: 'church-e2f46.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4Kq3rJdSa7lY2pLexi2vDNLwjlBcG7co',
    appId: '1:173813791952:ios:211ac452f75bf55742b2d5',
    messagingSenderId: '173813791952',
    projectId: 'church-e2f46',
    storageBucket: 'church-e2f46.firebasestorage.app',
    iosBundleId: 'com.example.church',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4Kq3rJdSa7lY2pLexi2vDNLwjlBcG7co',
    appId: '1:173813791952:ios:211ac452f75bf55742b2d5',
    messagingSenderId: '173813791952',
    projectId: 'church-e2f46',
    storageBucket: 'church-e2f46.firebasestorage.app',
    iosBundleId: 'com.example.church',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAwKQ460poruMSbQFZ9OP8SAf_2y2Uxw0A',
    appId: '1:173813791952:web:1e9124ef5c958b8b42b2d5',
    messagingSenderId: '173813791952',
    projectId: 'church-e2f46',
    authDomain: 'church-e2f46.firebaseapp.com',
    storageBucket: 'church-e2f46.firebasestorage.app',
    measurementId: 'G-YFMPMBC311',
  );
}
